import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import '../globals.css';
import { FunctionComponent, PropsWithChildren } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps extends PropsWithChildren {
	params: { locale: string };
}

const getLocale = (locale: string): 'US' | 'FR' | 'TR' | undefined => {
	if (locale === 'en') return 'US';
	if (locale === 'fr') return 'FR';
	if (locale === 'tr') return 'TR';
};

const RootLayout: FunctionComponent<RootLayoutProps> = async ({
	children,
	params: { locale },
}) => {
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<NextIntlClientProvider messages={messages}>
					<Header locale={getLocale(locale)} />
					<div className='pt-16 sm:pt-20 md:pt-24'>{children}</div>
					<Footer />
					<Toaster
						richColors
						closeButton
						duration={3000}
						expand={true}
						gap={8}
						pauseWhenPageIsHidden={true}
						position='bottom-right'
						theme='system'
					/>
				</NextIntlClientProvider>
			</body>
		</html>
	);
};

export default RootLayout;
